/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
import login.Establish_Connection;

/*
 * MemberList.java
 *
 * Created on 21 Jun, 2015, 3:45:07 PM
 */

/**
 *
 * @author pranjal
 */
public class NewClass extends javax.swing.JFrame {

     Establish_Connection ec=new Establish_Connection();
     int r=0;
    /** Creates new form MemberList */
    public NewClass() {
        initComponents();
        JTable jTable1=new JTable();
        Object[] columns={"S.NO","NAME","EMAIL-ID","CONTACT","BOOK ISSUED","ISSUE DATE","RETURN DATE"};
        DefaultTableModel dtm=new DefaultTableModel();
        dtm.setColumnIdentifiers(columns);
        jTable1.setModel(dtm);
        jTable1.setRowHeight(20);
        try{
        ec.pst=ec.con.prepareStatement("select * from member");
        ec.rs=ec.pst.executeQuery();
        while(ec.rs.next())
        {
            Object[] row= new Object[7];
            row[0]="12";
            row[1]="12";
            row[2]="12";
            row[3]="12";
            row[4]="12";
            row[5]="12";
            row[6]="12";
          /*jTable1.setValueAt(ec.rs.getString(1), r, 0);
          jTable1.setValueAt(ec.rs.getString(2), r, 1);
          jTable1.setValueAt(ec.rs.getString(3), r, 2);
          jTable1.setValueAt(ec.rs.getString(4), r, 3);
          jTable1.setValueAt(ec.rs.getString(5), r, 4);
          jTable1.setValueAt(ec.rs.getString(6), r, 5);
          jTable1.setValueAt(ec.rs.getString(7), r, 6);
          
          r++;*/
        }
        }
        catch(Exception e)
        {
            System.out.println(e);
        }

    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 743, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 301, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>                        

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NewClass().setVisible(true);
                
            }
        });
    }

    // Variables declaration - do not modify                     
    // End of variables declaration                   

}
